// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    $('#footer').html("try");
    return $('a').each(function(index, element) {
      return console.log(element);
    });
  });

}).call(this);
